### ISSUE TITLE
dev fails to compile: #3448's digest test constructs CostRegression with the pre-#3441 shape — its checks went green ten minutes before BaselineP95MsPerRun became required

### ISSUE THREAD

**Issue by erikdarlingdata** [erikdarlingdata/PerformanceMonitor#3457]
`dev` is red as of the #3448 merge. Run [34964638655](https://github.com/erikdarlingdata/PerformanceMonitor/actions/runs/34964638655) (push of squash commit `602211f7`, 2026-09-15T11:41:22Z) fails to compile the test project:

```
Darling\Darling.Tests\CollectorCostDigestTests.cs(59,9): error CS7036: There is no argument given that
corresponds to the required parameter 'BaselineP95MsPerRun' of
'DarlingCollectorCostReader.CostRegression.CostRegression(int, string, string, long, double, DateTime, long, double, double, double)'
```

Both test jobs fail on it — `Darling PostgreSQL tests` at the build step, and `build` downstream when `dotnet run --no-build` can't find a `Darling.Tests.exe` that was never produced. The Linux build and the whole-tree guards pass; nothing here is environmental.

## How two green PRs made a red dev

This is a semantic conflict between two merges that never compiled together until they landed:

- **02:35:57Z** — #3448's final CI run went green against `dev` as it stood at that moment (PR head `fa6b6bae`).
- **02:45:36Z** — #3441 merged as `3d294671`, adding `BaselineP95MsPerRun` as a *required* constructor parameter on `DarlingCollectorCostReader.CostRegression` and updating every caller that existed at the time. #3448's new `CollectorCostDigestTests.cs` did not exist yet, so it wasn't updated.
- **11:41:19Z** — #3448, held as a draft for its acceptance gate, merged without a fresh check run. The first build anywhere to compile the digest test against the post-#3441 record shape was `dev`'s own, and it failed.

The gap is ten minutes at the front and nine hours at the back: the checks were honest when they ran, and stale by the time the merge button existed.

## Classification and disposition

Deterministic compile regression — not rerun (rerunning recompiles the same source). The fix shape is one line: the `CostRegression` construction at `CollectorCostDigestTests.cs:59` needs a `BaselineP95MsPerRun` argument with whatever baseline the scenario intends. Whoever picks this up may also want the digest test to exercise the p95 field on purpose, since #3441's whole point was that the mean baseline understated dispersion — the test now has the parameter available either way.

Worth a thought for process: a draft that waits hours between last-green and merge is exactly the window where this recurs. Re-running checks on un-draft (or before merging anything whose base moved) would have caught this at 11:40Z instead of 11:43Z.

— filed by `ci-sentinel` (scheduled CI watch)

**Comment by erikdarlingdata** [comment]
Closed by #3459 (merged to dev), which carries the one-line reserved fix: the digest factory now passes CostRegression's tenth argument by name, so dev's Darling.Tests compiles against the post-#3441 shape.
